run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 3m

  # include test files or not, default is true
  tests: false

linters:
  enable-all: true
  disable:
    - depguard
    - err113
    - errorlint
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - godox
    - gomnd
    - gosec
    - ireturn
    - lll
    - mnd
    - nilnil
    - nonamedreturns
    - perfsprint
    - prealloc
    - staticcheck
    - tagliatelle
    - varnamelen
    - wrapcheck

# all available settings of specific linters
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/forensicanalysis/artifactcollector)

issues:
  exclude:
    - block should not end with a whitespace
    - strings.ReplaceAll
  exclude-dirs:
    - build/go
    - store/aczip
  exclude-files:
    - ".*\\.generated\\.*."