# Predefined opinionated collections

name: DefaultCollection1
doc: Predefined opinionated collections
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        - 'FOR500'
        - 'WindowsComputerName'
        - 'WindowsEventLogs'
        - 'WindowsHotfixes'
        - 'WindowsNetworkInterfaceInformation'
        - 'WindowsPersistence'
        - 'WindowsRunKeys'
        - 'WindowsServices'
        - 'WindowsUninstallKeys'
        - 'WindowsUSBInformation'
    supported_os: [ Windows ]
  - type: ARTIFACT_GROUP
    attributes:
      names:
        # - 'BrowserCache'
        - 'BrowserHistory'
        - 'LinuxIPTablesRulesCommand'
        - 'LinuxAtJobsFiles'
        - 'LinuxAuditLogFiles'
        - 'LinuxCronTabFiles'
        - 'LinuxHostnameFile'
    supported_os: [ Linux ]
  - type: ARTIFACT_GROUP
    attributes:
      names:
        # - 'BrowserCache'
        - 'BrowserHistory'
        - 'MacOSAtJobsFile'
        - 'MacOSAuditLogFiles'
        - 'MacOSBashHistoryFile'
        - 'MacOSCronTabFile'
        - 'MacOSHostsFile'
        - 'MacOSLastlogFile'
        - 'MacOSMiscLogFiles'
        - 'MacOSRecentItemsFiles'
        - 'MacOSSystemLogFiles'
        - 'MacOSUserTrashFiles'
    supported_os: [ Darwin ]
supported_os: [ Darwin,Linux,Windows ]
---
# Artifacts from the SANS FOR500 course

name: FOR500
doc: Windows Forensic Analysis
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        - WindowsBrowserArtifacts
        - WindowsProgramExecution
        - WindowsDeletedFiles
        - WindowsNetworkActivity
        # - WindowsFileOpening
        - AccountUsage
        - ExternalDevice
supported_os: [ Windows ]
---
name: WindowsBrowserArtifacts
doc: WindowsBrowserArtifacts
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        - WindowsOpenSaveMRU
        - WindowsOpenSavePidlMRU
        # EmailAttachments
        # SkypeMainDirectory is only for macos
        # BrowserCache not collected by default
        - BrowserHistory
        # AdsZoneIdentifier
supported_os: [ Windows ]
---
name: WindowsProgramExecution
doc: Program Execution
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        # UserAssist
        - WindowsActivitiesCacheDatabase
        - WindowsMostRecentApplication
        - WindowsAppCompatCache # Shimcache
        # JumpLists
        - WindowsAMCacheHveFile
        - WindowsSystemResourceUsageMonitorDatabaseFile
        # BAM/DAM
        # LastVisitedMRU
        - WindowsPrefetchFiles
supported_os: [ Windows ]
---
name: WindowsDeletedFiles
doc: Deleted Files
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        # ACMRU
        # Thumbcache
        # Thumbs.db
        # IEEdgeFile -> WindowsBrowserArtifacts
        # WordWheelQuery
        - WindowsRecycleBin
        # LastVisitedMRU -> WindowsProgramExecution
supported_os: [ Windows ]
---
name: WindowsNetworkActivity
doc: Network Activity
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        - WindowsTimezone
        - InternetExplorerCookiesFile
        # NetworkHistory
        # WLANEventLog
        # BrowserSearchTerms -> WindowsBrowserArtifacts
        # WindowsSystemResourceUsageMonitorDatabaseFile -> WindowsProgramExecution
supported_os: [ Windows ]
# ---
# name: WindowsFileOpening
# doc: File Opening
# sources:
# - type: ARTIFACT_GROUP
#   attributes:
#     names:
#       # WindowsOpenSaveMRU -> WindowsBrowserArtifacts
#       # RecentFiles
#       # JumpLists -> WindowsProgramExecution
#       # ShellBags
#       # LNKFiles
#       # WindowsPrefetchFiles -> WindowsProgramExecution
#       # LastVisitedMRU -> WindowsProgramExecution
#       # IEEdgeFile -> WindowsBrowserArtifacts
#       # OfficeRecentFiles
# supported_os: [Windows]
---
name: AccountUsage
doc: Account Usage
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        - WindowsSystemRegistryFiles
        - WindowsXMLEventLogSecurityFile
supported_os: [ Windows ]
---
name: ExternalDevice
doc: External Device
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        # KeyIdentification
        - WindowsSetupApiLogs
        # User
        # PnPEvents
        # VolumeSerialNumber
        # DriverLetter
        # LNKFiles -> WindowsFileOpening
supported_os: [ Windows ]
