# Linux specific artifacts.

name: LinuxIPTablesRulesCommand
doc: List IPTables rules.
sources:
  - type: COMMAND
    attributes:
      args: [ "-L", "-n", "-v" ]
      cmd: /sbin/iptables
supported_os: [ Linux ]
---
name: LinuxAtJobsFiles
doc: Linux at jobs.
sources:
  - type: FILE
    attributes: { paths: [ '/var/spool/at/*' ] }
supported_os: [ Linux ]
---
name: LinuxAuditLogFiles
doc: Linux audit log files.
sources:
  - type: FILE
    attributes: { paths: [ '/var/log/audit/*' ] }
supported_os: [ Linux ]
---
name: LinuxCronTabFiles
doc: Crontab files.
sources:
  - type: FILE
    attributes:
      paths:
        - '/etc/crontab'
        - '/etc/cron.d/*'
        - '/var/spool/cron/**'
supported_os: [ Linux ]
---
name: LinuxHostnameFile
doc: Linux hostname file.
sources:
  - type: FILE
    attributes: { paths: [ '/etc/hostname' ] }
supported_os: [ Linux ]
---
name: LinuxPasswdFile
doc: |
  Linux passwd file.

  A passwd file consist of colon separated values in the format:
  username:password:uid:gid:full name:home directory:shell
sources:
  - type: FILE
    attributes: { paths: [ '/etc/passwd' ] }
    provides:
      - key: users.homedir
        regex: '.*:(.*?):.*'
supported_os: [ Linux ]
---
name: LinuxHomePath
doc: Users directories in /home
sources:
  - type: PATH
    attributes: { paths: [ '/home/*' ] }
    provides:
      - key: users.homedir
supported_os: [ Linux ]
