# Web browser artifacts.

name: BrowserHistory
doc: Web browser history of multiple web browsers.
sources:
  - type: ARTIFACT_GROUP
    attributes:
      names:
        - 'ChromiumBasedBrowsersHistoryDatabaseFile'
        - 'FirefoxHistoryFile'
        - 'InternetExplorerHistoryFile'
        - 'OperaHistoryFile'
        - 'SafariDownloadFile'
        - 'SafariHistoryFile'
supported_os: [ Darwin,Linux,Windows ]
---
name: ChromiumBasedBrowsersHistoryDatabaseFile
doc: >-
  Browsing history database file for multiple Chromium-based browsers, such as
  Google Chrome, Brave, Chromium, Yandex, Opera, Edge, EdgeBeta.
sources:
  - type: FILE
    attributes:
      paths:
        - '%%users.homedir%%/Library/Application Support/BraveSoftware/Brave-Browser/*/Archived
      History'
        - '%%users.homedir%%/Library/Application Support/BraveSoftware/Brave-Browser/*/Archived
      History-journal'
        - '%%users.homedir%%/Library/Application Support/BraveSoftware/Brave-Browser/*/History'
        - '%%users.homedir%%/Library/Application Support/BraveSoftware/Brave-Browser/*/History-journal'
        - '%%users.homedir%%/Library/Application Support/Chromium/*/Archived History'
        - '%%users.homedir%%/Library/Application Support/Chromium/*/Archived History-journal'
        - '%%users.homedir%%/Library/Application Support/Chromium/*/History'
        - '%%users.homedir%%/Library/Application Support/Chromium/*/History-journal'
        - '%%users.homedir%%/Library/Application Support/Google/Chrome Canary/*/Archived
      History'
        - '%%users.homedir%%/Library/Application Support/Google/Chrome Canary/*/Archived
      History-journal'
        - '%%users.homedir%%/Library/Application Support/Google/Chrome Canary/*/History'
        - '%%users.homedir%%/Library/Application Support/Google/Chrome Canary/*/History-journal'
        - '%%users.homedir%%/Library/Application Support/Google/Chrome/*/Archived History'
        - '%%users.homedir%%/Library/Application Support/Google/Chrome/*/Archived History-journal'
        - '%%users.homedir%%/Library/Application Support/Google/Chrome/*/History'
        - '%%users.homedir%%/Library/Application Support/Google/Chrome/*/History-journal'
        - '%%users.homedir%%/Library/Application Support/Microsoft Edge Beta/*/Archived
      History'
        - '%%users.homedir%%/Library/Application Support/Microsoft Edge Beta/*/Archived
      History-journal'
        - '%%users.homedir%%/Library/Application Support/Microsoft Edge Beta/*/History'
        - '%%users.homedir%%/Library/Application Support/Microsoft Edge Beta/*/History-journal'
        - '%%users.homedir%%/Library/Application Support/Microsoft Edge/*/Archived History'
        - '%%users.homedir%%/Library/Application Support/Microsoft Edge/*/Archived History-journal'
        - '%%users.homedir%%/Library/Application Support/Microsoft Edge/*/History'
        - '%%users.homedir%%/Library/Application Support/Microsoft Edge/*/History-journal'
        - '%%users.homedir%%/Library/Application Support/Yandex/YandexBrowser/*/Archived
      History'
        - '%%users.homedir%%/Library/Application Support/Yandex/YandexBrowser/*/Archived
      History-journal'
        - '%%users.homedir%%/Library/Application Support/Yandex/YandexBrowser/*/History'
        - '%%users.homedir%%/Library/Application Support/Yandex/YandexBrowser/*/History-journal'
        - '%%users.homedir%%/Library/Application Support/com.operasoftware.Opera/*/Archived
      History'
        - '%%users.homedir%%/Library/Application Support/com.operasoftware.Opera/*/Archived
      History-journal'
        - '%%users.homedir%%/Library/Application Support/com.operasoftware.Opera/*/History'
        - '%%users.homedir%%/Library/Application Support/com.operasoftware.Opera/*/History-journal'
    supported_os:
      - Darwin
  - type: FILE
    attributes:
      paths:
        - '%%users.homedir%%/.config/BraveSoftware/Brave-Browser/*/Archived History'
        - '%%users.homedir%%/.config/BraveSoftware/Brave-Browser/*/Archived History-journal'
        - '%%users.homedir%%/.config/BraveSoftware/Brave-Browser/*/History'
        - '%%users.homedir%%/.config/BraveSoftware/Brave-Browser/*/History-journal'
        - '%%users.homedir%%/.config/chrome-remote-desktop/chrome-config/google-chrome/*/Archived
      History'
        - '%%users.homedir%%/.config/chrome-remote-desktop/chrome-config/google-chrome/*/Archived
      History-journal'
        - '%%users.homedir%%/.config/chrome-remote-desktop/chrome-config/google-chrome/*/History'
        - '%%users.homedir%%/.config/chrome-remote-desktop/chrome-config/google-chrome/*/History-journal'
        - '%%users.homedir%%/.config/chrome-remote-desktop/chrome-profile/*/Archived History'
        - '%%users.homedir%%/.config/chrome-remote-desktop/chrome-profile/*/Archived History-journal'
        - '%%users.homedir%%/.config/chrome-remote-desktop/chrome-profile/*/History'
        - '%%users.homedir%%/.config/chrome-remote-desktop/chrome-profile/*/History-journal'
        - '%%users.homedir%%/.config/chromium/*/Archived History'
        - '%%users.homedir%%/.config/chromium/*/Archived History-journal'
        - '%%users.homedir%%/.config/chromium/*/History'
        - '%%users.homedir%%/.config/chromium/*/History-journal'
        - '%%users.homedir%%/.config/google-chrome-beta/*/Archived History'
        - '%%users.homedir%%/.config/google-chrome-beta/*/Archived History-journal'
        - '%%users.homedir%%/.config/google-chrome-beta/*/History'
        - '%%users.homedir%%/.config/google-chrome-beta/*/History-journal'
        - '%%users.homedir%%/.config/google-chrome/*/Archived History'
        - '%%users.homedir%%/.config/google-chrome/*/Archived History-journal'
        - '%%users.homedir%%/.config/google-chrome/*/History'
        - '%%users.homedir%%/.config/google-chrome/*/History-journal'
        - '%%users.homedir%%/.config/microsoft-edge/*/Archived History'
        - '%%users.homedir%%/.config/microsoft-edge/*/Archived History-journal'
        - '%%users.homedir%%/.config/microsoft-edge/*/History'
        - '%%users.homedir%%/.config/microsoft-edge/*/History-journal'
        - '%%users.homedir%%/.config/opera/*/Archived History'
        - '%%users.homedir%%/.config/opera/*/Archived History-journal'
        - '%%users.homedir%%/.config/opera/*/History'
        - '%%users.homedir%%/.config/opera/*/History-journal'
        - '%%users.homedir%%/.config/yandex-browser-beta/*/Archived History'
        - '%%users.homedir%%/.config/yandex-browser-beta/*/Archived History-journal'
        - '%%users.homedir%%/.config/yandex-browser-beta/*/History'
        - '%%users.homedir%%/.config/yandex-browser-beta/*/History-journal'
        - '%%users.homedir%%/snap/chromium/common/chromium/*/Archived History'
        - '%%users.homedir%%/snap/chromium/common/chromium/*/Archived History-journal'
        - '%%users.homedir%%/snap/chromium/common/chromium/*/History'
        - '%%users.homedir%%/snap/chromium/common/chromium/*/History-journal'
    supported_os:
      - Linux
  - type: FILE
    attributes:
      paths:
        - '%%users.appdata%%\Brave\*\Archived History'
        - '%%users.appdata%%\Brave\*\Archived History-journal'
        - '%%users.appdata%%\Brave\*\History'
        - '%%users.appdata%%\Brave\*\History-journal'
        - '%%users.appdata%%\BraveSoftware\Brave-Browser\User Data\*\History'
        - '%%users.appdata%%\BraveSoftware\Brave-Browser\User Data\*\History-journal'
        - '%%users.appdata%%\Opera Software\Opera Stable\*\Archived History'
        - '%%users.appdata%%\Opera Software\Opera Stable\*\Archived History-journal'
        - '%%users.appdata%%\Opera Software\Opera Stable\*\History'
        - '%%users.appdata%%\Opera Software\Opera Stable\*\History-journal'
        - '%%users.localappdata%%\Chromium\*\Archived History'
        - '%%users.localappdata%%\Chromium\*\Archived History-journal'
        - '%%users.localappdata%%\Chromium\*\History'
        - '%%users.localappdata%%\Chromium\*\History-journal'
        - '%%users.localappdata%%\Chromium\User Data\*\Archived History'
        - '%%users.localappdata%%\Chromium\User Data\*\Archived History-journal'
        - '%%users.localappdata%%\Chromium\User Data\*\History'
        - '%%users.localappdata%%\Chromium\User Data\*\History-journal'
        - '%%users.localappdata%%\Google\Chrome SxS\User Data\*\Archived History'
        - '%%users.localappdata%%\Google\Chrome SxS\User Data\*\Archived History-journal'
        - '%%users.localappdata%%\Google\Chrome SxS\User Data\*\History'
        - '%%users.localappdata%%\Google\Chrome SxS\User Data\*\History-journal'
        - '%%users.localappdata%%\Google\Chrome\User Data\*\Archived History'
        - '%%users.localappdata%%\Google\Chrome\User Data\*\Archived History-journal'
        - '%%users.localappdata%%\Google\Chrome\User Data\*\History'
        - '%%users.localappdata%%\Google\Chrome\User Data\*\History-journal'
        - '%%users.localappdata%%\Microsoft\Edge Beta\User Data\*\Archived History'
        - '%%users.localappdata%%\Microsoft\Edge Beta\User Data\*\Archived History-journal'
        - '%%users.localappdata%%\Microsoft\Edge Beta\User Data\*\History'
        - '%%users.localappdata%%\Microsoft\Edge Beta\User Data\*\History-journal'
        - '%%users.localappdata%%\Microsoft\Edge\User Data\*\Archived History'
        - '%%users.localappdata%%\Microsoft\Edge\User Data\*\Archived History-journal'
        - '%%users.localappdata%%\Microsoft\Edge\User Data\*\History'
        - '%%users.localappdata%%\Microsoft\Edge\User Data\*\History-journal'
        - '%%users.localappdata%%\Yandex\YandexBrowser\User Data\*\Archived History'
        - '%%users.localappdata%%\Yandex\YandexBrowser\User Data\*\Archived History-journal'
        - '%%users.localappdata%%\Yandex\YandexBrowser\User Data\*\History'
        - '%%users.localappdata%%\Yandex\YandexBrowser\User Data\*\History-journal'
      separator: \
    supported_os:
      - Windows
supported_os:
  - Darwin
  - Linux
  - Windows
---
name: FirefoxHistoryFile
doc: Firefox browser history (places.sqlite).
sources:
  - type: FILE
    attributes:
      paths:
        - '%%users.localappdata%%\Mozilla\Firefox\Profiles\*\places.sqlite'
        - '%%users.localappdata%%\Mozilla\Firefox\Profiles\*\places.sqlite-wal'
        - '%%users.appdata%%\Mozilla\Firefox\Profiles\*\places.sqlite'
        - '%%users.localappdata%%\Mozilla\Firefox\Profiles\*\places.sqlite-wal'
      separator: '\'
    supported_os: [ Windows ]
  - type: FILE
    attributes:
      paths:
        - '%%users.homedir%%/Library/Application Support/Firefox/Profiles/*/places.sqlite'
        - '%%users.homedir%%/Library/Application Support/Firefox/Profiles/*/places.sqlite-wal'
    supported_os: [ Darwin ]
  - type: FILE
    attributes:
      paths:
        - '%%users.homedir%%/.mozilla/firefox/*/places.sqlite'
        - '%%users.homedir%%/.mozilla/firefox/*/places.sqlite-wal'
        - '%%users.homedir%%/snap/firefox/common/.mozilla/firefox/*/places.sqlite'
        - '%%users.homedir%%/snap/firefox/common/.mozilla/firefox/*/places.sqlite-wal'
    supported_os: [ Linux ]
supported_os: [ Windows,Darwin,Linux ]
---
name: InternetExplorerBrowserHelperObjectsRegistryKeys
doc: Loaded on Internet Explorer startup
sources:
  - type: REGISTRY_KEY
    attributes:
      keys:
        - 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\Browser Helper Objects\*'
        - 'HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\Browser Helper Objects\*'
supported_os: [ Windows ]
---
name: InternetExplorerCookiesFile
doc: |
  Microsoft Internet Explorer (MSIE) browser cookies.

  * MSIE 4 - 9 Cache files (index.dat)
sources:
  - type: FILE
    attributes:
      paths:
        - '%%users.appdata%%\Microsoft\Windows\Cookies\index.dat'
        - '%%users.appdata%%\Microsoft\Windows\Cookies\Low\index.dat'
        - '%%users.userprofile%%\Cookies\index.dat'
      separator: '\'
supported_os: [ Windows ]
---
name: InternetExplorerHistoryFile
doc: |
  Microsoft Internet Explorer (MSIE) browser history.

  * MSIE 4 - 9 Cache files (index.dat);
  * MSIE 10 WebCacheV*.dat files.
sources:
  - type: FILE
    attributes:
      paths:
        - '%%users.appdata%%\Microsoft\Windows\IEDownloadHistory\index.dat'
        - '%%users.localappdata%%\Microsoft\Feeds Cache\index.dat'
        - '%%users.localappdata%%\Microsoft\Windows\History\History.IE5\*\index.dat'
        - '%%users.localappdata%%\Microsoft\Windows\History\History.IE5\index.dat'
        - '%%users.localappdata%%\Microsoft\Windows\History\Low\History.IE5\*\index.dat'
        - '%%users.localappdata%%\Microsoft\Windows\History\Low\History.IE5\index.dat'
        - '%%users.localappdata%%\Microsoft\Windows\Temporary Internet Files\Content.IE5\index.dat'
        - '%%users.localappdata%%\Microsoft\Windows\Temporary Internet Files\Low\Content.IE5\index.dat'
        - '%%users.localappdata%%\Microsoft\Windows\WebCache\WebCacheV*.dat'
        - '%%users.userprofile%%\Local Settings\History\History.IE5\index.dat'
        - '%%users.userprofile%%\Local Settings\History\History.IE5\*\index.dat'
        - '%%users.userprofile%%\Local Settings\History\Temporary Internet Files\Content.IE5\index.dat'
        - '%%users.userprofile%%\Local Settings\Temporary Internet Files\Content.IE5\index.dat'
      separator: '\'
supported_os: [ Windows ]
---
name: OperaHistoryFile
doc: Opera browser history (global_history.dat).
sources:
  - type: FILE
    attributes: { paths: [ '%%users.homedir%%/Library/Opera/global_history.dat' ] }
    supported_os: [ Darwin ]
  - type: FILE
    attributes: { paths: [ '%%users.homedir%%/.opera/global_history.dat' ] }
    supported_os: [ Linux ]
  - type: FILE
    attributes:
      paths:
        - '%%users.appdata%%\Opera\Opera\global_history.dat'
        - '%%users.appdata%%\Opera Software\Opera Stable\History'
        - '%%users.appdata%%\Opera Software\Opera Stable\History-journal'
      separator: '\'
    supported_os: [ Windows ]
supported_os: [ Windows,Darwin,Linux ]
---
name: SafariDownloadFile
doc: Safari downloads history (Downloads.plist).
sources:
  - type: FILE
    attributes: { paths: [ '%%users.homedir%%/Library/Safari/Downloads.plist' ] }
    supported_os: [ Darwin ]
  - type: FILE
    attributes:
      paths:
        - '%%users.localappdata%%\Apple Computer\Safari\Downloads.plist'
        - '%%users.appdata%%\Apple Computer\Safari\Downloads.plist'
      separator: '\'
    supported_os: [ Windows ]
supported_os: [ Darwin, Windows ]
---
name: SafariHistoryFile
doc: Safari browser history (History.plist).
sources:
  - type: FILE
    attributes:
      paths:
        - '%%users.localappdata%%\Apple Computer\Safari\History.plist'
        - '%%users.appdata%%\Apple Computer\Safari\History.plist'
      separator: '\'
    supported_os: [ Windows ]
  - type: FILE
    attributes:
      paths:
        - '%%users.homedir%%/Library/Safari/History.plist'
        - '%%users.homedir%%/Library/Safari/History.db'
        - '%%users.homedir%%/Library/Safari/History.db-wal'
    supported_os: [ Darwin ]
supported_os: [ Windows, Darwin ]
